language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

service:
  - redis-server

matrix:
    include:
        - php: 7.1
          env: deps=low
    fast_finish: true

before_script:
  - pecl channel-update pecl.php.net
  - echo '' | pecl install redis-5.0.0
  - echo '' | pecl install yac-2.0.2
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = yac.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "yac.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi

script:
  - vendor/bin/phpunit
